# mybatis_config
mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    config-locations: classpath:mybatis/mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true
    type-aliases-package: com.jcf.suchness.model.db
#水质监测ip端口
shuizhihost:
   183.208.120.208:9093
#datasource
spring:
    gson:
      date-format:  yyyy-MM-dd HH:mm:ss
    fastjson:
      date-format:  yyyy-MM-dd HH:mm:ss
    session:
      store-type: none
    datasource:
      dsopc:
        name: 污水泵站
        url: jdbc:mysql://183.208.120.208:33306/opc?characterEncoding=UTF-8&userServerPrepStmts=true&rewriteBatchedStatements=true
        username: root
        password: Xkh@mysql_2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      dsstation:
        name: 水质监测
        url: jdbc:sqlserver://183.208.120.208:14333;DatabaseName=prd_env_dts
        username: sa
        password: sa123123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-id: com.microsoft.sqlserver.jdbc.SQLServerDriver
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT getdate()
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        #filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      dsyinjing:
        name: dsyinjing
        url: jdbc:sqlserver://183.208.120.208:1444;DatabaseName=rushi
        #url: jdbc:sqlserver://192.168.1.204:1433;DatabaseName=rushi
        username: ywj
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-id: com.microsoft.sqlserver.jdbc.SQLServerDriver
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT getdate()
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      dssuqian:
          name: 数学模型
          url: jdbc:mysql://localhost:3306/mathmodel
          username: root
          password: 123456
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          # 初始化大小，最小，最大
          initialSize: 5
          minIdle: 5
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: true
          testOnReturn: true
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 1886